[tox]
envlist = py310, py311

[gh-actions]
python =
    3.10: py310
    3.11: py311

[testenv]
setenv =
    PYTHONPATH = {toxinidir}/src
deps =
    -e {toxinidir}[dev]
commands =
    pip install -e .
    pytest --cov=src/pyFDN --cov-report=term-missing --cov-report=xml {posargs:tests}

