#!/usr/bin/env python3
"""
created by Facundo Franchino, early October 2025

non-regression test for one-pole absorption FDN implementation.

this test compares pyFDN output with fdnToolbox (MATLAB) reference data

the test requires a reference .mat file generated by running:
fdnToolbox/Examples/example_onePoleAbsorption_export.m
"""

import os
import sys
import numpy as np
import pytest

# add the src directory to python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from pyFDN.auxiliary.one_pole_absorption import one_pole_absorption
from pyFDN.generate.random_orthogonal import random_orthogonal

try:
    import scipy.io
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False

# path to reference data
REFERENCE_MAT_FILE = os.path.join(
    os.path.dirname(__file__), 
    '..', 
    'tests', 
    'reference_files', 
    'onePoleAbsorption_reference.mat'
)


def load_matlab_reference():
    """load reference data from MATLAB export."""
    if not SCIPY_AVAILABLE:
        pytest.skip("scipy not available for loading .mat files")
    
    if not os.path.exists(REFERENCE_MAT_FILE):
        pytest.skip(f"ref file not found: {REFERENCE_MAT_FILE}")
    
    mat_data = scipy.io.loadmat(REFERENCE_MAT_FILE)
    return mat_data['export_data'][0, 0]  # MATLAB struct format


@pytest.mark.skipif(not SCIPY_AVAILABLE, reason="scipy not available")
def test_one_pole_absorption_coefficients():
    """test that pyFDN generates same absorption coefficients as MATLAB."""
    
    # load MATLAB reference
    ref = load_matlab_reference()
    
    # extract reference parameters
    RT_DC = float(ref['RT_DC'].item())
    RT_NY = float(ref['RT_NY'].item())
    delays = ref['delays'].flatten()
    fs = float(ref['fs'].item())
    
    # generate coefficients using pyFDN
    b_python, a_python = one_pole_absorption(RT_DC, RT_NY, delays, fs)
    
    # extract MATLAB coefficients
    b_matlab = ref['absorption_b']
    a_matlab = ref['absorption_a']
    
    # reshape Python outputs to match MATLAB format if needed
    # b coefficients: Python (4,1,1) -> MATLAB (4,1)
    if b_python.shape == (4, 1, 1) and b_matlab.shape == (4, 1):
        b_python = b_python.squeeze(-1)
    
    # a coefficients: both should be (4,1,2) but verify
    assert a_python.shape == a_matlab.shape, f"a shape mismatch: {a_python.shape} vs {a_matlab.shape}"
    assert b_python.shape == b_matlab.shape, f"b shape mismatch after reshape: {b_python.shape} vs {b_matlab.shape}"
    
    # compare values with tolerance for numerical differences
    np.testing.assert_allclose(b_python, b_matlab, rtol=1e-14, atol=1e-16,
                              err_msg="b coefficients don't match MATLAB reference")
    np.testing.assert_allclose(a_python, a_matlab, rtol=1e-14, atol=1e-16,
                              err_msg="a coefficients don't match MATLAB reference")


@pytest.mark.skipif(not SCIPY_AVAILABLE, reason="scipy not available")
def test_random_orthogonal_matrix():
    """test that both pyFDN and MATLAB generate valid orthogonal matrices."""
    
    # load MATLAB reference
    ref = load_matlab_reference()
    
    # extract MATLAB matrix
    matrix_matlab = ref['feedbackMatrix']
    
    # set same random seed as MATLAB (but RNG implementations differ)
    np.random.seed(1)
    
    # generate matrix using pyFDN
    N = int(ref['N'].item())
    matrix_python = random_orthogonal(N)
    
    # compare shapes
    assert matrix_python.shape == matrix_matlab.shape, \
        f"matrix shape mismatch: {matrix_python.shape} vs {matrix_matlab.shape}"
    
    # both should be orthogonal (can't compare values due to different RNGs)
    # test orthogonality of both matrices
    product_python = matrix_python.T @ matrix_python
    product_matlab = matrix_matlab.T @ matrix_matlab
    identity = np.eye(N)
    
    np.testing.assert_allclose(product_python, identity, rtol=1e-12, atol=1e-15,
                              err_msg="Python matrix is not orthogonal")
    np.testing.assert_allclose(product_matlab, identity, rtol=1e-12, atol=1e-15,
                              err_msg="MATLAB matrix is not orthogonal")


@pytest.mark.skipif(not SCIPY_AVAILABLE, reason="scipy not available") 
def test_delays_reproducibility():
    """test that delay generation is reproducible (depends on random seed)."""
    
    # load MATLAB reference
    ref = load_matlab_reference()
    
    # MATLAB delays from randi([50, 300]*10,[1,N]) with rng(1)
    delays_matlab = ref['delays'].flatten()
    
    # note: can't easily reproduce MATLAB's randi in Python
    # this test mainly documents the expected delays for verification
    expected_delays = np.array([1320, 1650, 2790, 550])  # from python example
    
    print(f"MATLAB delays: {delays_matlab}")
    print(f"Python delays: {expected_delays}")
    
    # this test documents that we're using specific delay values
    # the exact values depend on the random number generator implementation
    assert len(delays_matlab) == 4, "should have 4 delay lines"
    assert np.all(delays_matlab >= 500), "aall delays should be >= 500 samples"
    assert np.all(delays_matlab <= 3000), "all delays should be <= 3000 samples"


@pytest.mark.skipif(not SCIPY_AVAILABLE, reason="scipy not available")
def test_fdn_parameters_consistency():
    """test that basic FDN parameters match between MATLAB and Python."""
    
    # load MATLAB reference
    ref = load_matlab_reference()
    
    # test scalar parameters
    assert ref['fs'] == 48000, "sample rate should be 48000"
    assert ref['N'] == 4, "should have 4 delay lines"
    assert ref['RT_DC'] == 3.0, "RT_DC should be 3.0 seconds"
    assert ref['RT_NY'] == 0.1, "RT_NY should be 0.1 seconds"
    
    # test gain matrices
    inputGain_matlab = ref['inputGain']
    outputGain_matlab = ref['outputGain'] 
    direct_matlab = ref['direct']
    
    expected_input = np.ones((4, 1))
    expected_output = np.ones((1, 4))
    expected_direct = np.ones((1, 1))
    
    np.testing.assert_array_equal(inputGain_matlab, expected_input)
    np.testing.assert_array_equal(outputGain_matlab, expected_output)
    np.testing.assert_array_equal(direct_matlab, expected_direct)


def test_without_matlab_reference():
    """test basic functionality even without MATLAB reference file."""
    
    # test parameters
    fs = 48000
    RT_DC = 3.0
    RT_NY = 0.1
    delays = np.array([1320, 1650, 2790, 550])
    
    # test coefficient generation
    b, a = one_pole_absorption(RT_DC, RT_NY, delays, fs)
    
    # basic sanity checks
    assert b.shape[0] == len(delays), "b coefficients should match number of delays"
    assert a.shape[0] == len(delays), "a coefficients should match number of delays"
    assert np.all(np.isfinite(b)), "b coefficients should be finite"
    assert np.all(np.isfinite(a)), "a coefficients should be finite"
    
    # test orthogonal matrix generation
    np.random.seed(1)
    matrix = random_orthogonal(4)
    
    # test orthogonality
    product = matrix.T @ matrix
    identity = np.eye(4)
    np.testing.assert_allclose(product, identity, rtol=1e-12, atol=1e-15,
                              err_msg="generated matrix is not orthogonal")


if __name__ == "__main__":
    # run tests when executed directly
    pytest.main([__file__, "-v"])