"""Generate the audio gallery from the audio files packaged with pyFDN."""

from __future__ import annotations

import html
import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

DOCS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DOCS_DIR.parent
AUDIO_SOURCE_DIR = PROJECT_ROOT / "src" / "pyFDN" / "resources" / "audio"
AUDIO_REFERENCES_FILE = AUDIO_SOURCE_DIR / "metadata.json"
OUTPUT_FILE = DOCS_DIR / "audio_gallery.rst"
GITHUB_AUDIO_ROOT = (
    "https://raw.githubusercontent.com/artificial-audio/pyFDN/"
    "main/src/pyFDN/resources/audio/"
)

UNCATEGORIZED = "uncategorized"


@dataclass(frozen=True)
class AudioExample:
    path: Path
    category: str

    @property
    def filename(self) -> str:
        return self.path.name

    @property
    def display_label(self) -> str:
        return f"{self.filename}"

    @property
    def audio_url(self) -> str:
        relative = self.path.relative_to(AUDIO_SOURCE_DIR)
        return GITHUB_AUDIO_ROOT + quote(relative.as_posix())


def discover_audio_files() -> list[AudioExample]:
    examples = []
    for path in sorted(AUDIO_SOURCE_DIR.rglob("*.wav")):
        relative = path.relative_to(AUDIO_SOURCE_DIR)
        category = relative.parts[0] if len(relative.parts) > 1 else UNCATEGORIZED
        examples.append(AudioExample(path, category))
    return examples


def render_gallery(examples: list[AudioExample]) -> str:
    # Load audio metadata
    with open(AUDIO_REFERENCES_FILE, encoding="utf-8") as f:
        audio_references = {item["filename"]: item for item in json.load(f)}

    grouped: dict[str, list[AudioExample]] = defaultdict(list)
    for example in examples:
        grouped[example.category].append(example)

    categories = sorted(
        grouped, key=lambda name: (name == UNCATEGORIZED, name.casefold())
    )

    lines = [
        ".. This file is generated by docs/audio_gallery.py. Do not edit it manually.",
        "",
        "============",
        "Audio Gallery",
        "============",
        "",
        "Audio examples demonstrating ``pyFDN``. The gallery is generated",
        "automatically from every packaged ``.wav`` file, grouped by resource category.",
        "",
    ]

    for category in categories:
        entries = sorted(grouped[category], key=lambda item: item.filename.casefold())

        lines.extend(
            [
                category,
                "-" * len(category),
                "",
                ".. raw:: html",
                "",
            ]
        )

        for example in entries:
            label_html = html.escape(example.display_label)
            src = example.audio_url

            if example.filename in audio_references:
                audio_ref = audio_references[example.filename]

                title = html.escape(audio_ref["source"])
                url = html.escape(audio_ref["source_url"])
                creator = html.escape(audio_ref["creator"])
                license_name = html.escape(audio_ref["license"])
                license_url = html.escape(audio_ref["license_url"])

                lines.extend(
                    [
                        f"   <p>{label_html}<br>",
                        f'   Source: <a href="{url}">{title}</a> — {creator}<br>',
                        f'   Terms: <a href="{license_url}">{license_name}</a><br>',
                        "   <audio controls>",
                        f'       <source src="{src}" type="audio/wav">',
                        "       Your browser does not support the audio element.",
                        "   </audio>",
                        "   </p>",
                    ]
                )
            else:
                lines.extend(
                    [
                        f"   <p>{label_html}<br>",
                        "   <audio controls>",
                        f'       <source src="{src}" type="audio/wav">',
                        "       Your browser does not support the audio element.",
                        "   </audio>",
                        "   </p>",
                    ]
                )

        lines.append("")

    lines.extend(
        [
            "----",
            "",
            "All audio files can also be browsed in the repository's",
            "`packaged audio directory <https://github.com/artificial-audio/pyFDN/tree/main/src/pyFDN/resources/audio>`_.",
            "",
        ]
    )
    return "\n".join(lines)


def generate_audio_gallery(output_file: Path = OUTPUT_FILE) -> str:
    examples = discover_audio_files()
    rendered = render_gallery(examples)
    output_file.write_text(rendered, encoding="utf-8")
    return rendered


if __name__ == "__main__":
    generate_audio_gallery()
