"""Generate the audio gallery from the .wav files under src/pyFDN/audio."""

from __future__ import annotations

import base64
import html
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DOCS_DIR.parent
AUDIO_SOURCE_DIR = PROJECT_ROOT / "src" / "pyFDN" / "audio"
OUTPUT_FILE = DOCS_DIR / "audio_gallery.rst"
GITHUB_AUDIO_ROOT = (
    "https://raw.githubusercontent.com/"
    "artificial-audio/pyFDN/main/src/pyFDN/audio/"
)

UNCATEGORIZED = "uncategorized"


@dataclass(frozen=True)
class AudioExample:
    path: Path
    category: str

    @property
    def filename(self) -> str:
        return self.path.name

    @property
    def display_label(self) -> str:
        return f"{self.filename}"

    @property
    def audio_url(self) -> str:
        relative = self.path.relative_to(AUDIO_SOURCE_DIR)
        return GITHUB_AUDIO_ROOT + relative.as_posix()


def discover_audio_files() -> list[AudioExample]:
    examples = []
    for path in sorted(AUDIO_SOURCE_DIR.rglob("*.wav")):
        relative = path.relative_to(AUDIO_SOURCE_DIR)
        category = relative.parts[0] if len(relative.parts) > 1 else UNCATEGORIZED
        examples.append(AudioExample(path, category))
    return examples


def render_gallery(examples: list[AudioExample]) -> str:
    grouped: dict[str, list[AudioExample]] = defaultdict(list)
    for example in examples:
        grouped[example.category].append(example)

    categories = sorted(grouped, key=lambda name: (name == UNCATEGORIZED, name.casefold()))

    lines = [
        ".. This file is generated by docs/audio_gallery.py. Do not edit it manually.",
        "",
        "============",
        "Audio Gallery",
        "============",
        "",
        "Audio examples demonstrating ``pyFDN``. The gallery is generated",
        "automatically from every ``.wav`` file under ``src/pyFDN/audio/``, grouped",
        "by the subfolder each file is located in.",
        "",
    ]

    for category in categories:
        entries = sorted(grouped[category], key=lambda item: item.filename.casefold())

        lines.extend(
            [
                category,
                "-" * len(category),
                "",
                ".. raw:: html",
                "",
            ]
        )

        for example in entries:
            label_html = html.escape(example.display_label)
            src = example.audio_url
            lines.extend(
                [
                    f"   <p>{label_html}<br>",
                    "   <audio controls>",
                    f"       <source src=\"{src}\" type=\"audio/wav\">",
                    "       Your browser does not support the audio element.",
                    "   </audio>",
                    "   </p>",
                ]
            )

        lines.append("")

    lines.extend(
        [
            "----",
            "",
            "All audio files can also be browsed in the repository's",
            "`audio directory <https://github.com/artificial-audio/pyFDN/tree/main/src/pyFDN/audio>`_.",
            "",
        ]
    )
    return "\n".join(lines)


def generate_gallery(output_file: Path = OUTPUT_FILE) -> str:
    examples = discover_audio_files()
    rendered = render_gallery(examples)
    output_file.write_text(rendered, encoding="utf-8")
    return rendered


if __name__ == "__main__":
    generate_gallery()