"""Generate the examples gallery from the marimo notebooks."""

from __future__ import annotations

import ast
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = DOCS_DIR.parent
EXAMPLES_DIR = PROJECT_ROOT / "examples"
OUTPUT_FILE = DOCS_DIR / "examples_gallery.rst"

CATEGORY_ORDER = (
    "Getting Started",
    "Feedback Matrices",
    "Absorption & Decay",
    "Analysis & Verification",
    "Optimization",
    "Allpass FDNs",
    "Special FDNs",
    "Representations",
    "Export & Deployment",
)


@dataclass(frozen=True)
class Example:
    path: Path
    title: str
    description: str
    category: str

    @property
    def output_name(self) -> str:
        relative = self.path.relative_to(EXAMPLES_DIR).with_suffix("")
        return "_".join(relative.parts)


def _markdown_blocks(path: Path) -> list[str]:
    """Return literal Markdown strings passed to ``mo.md`` calls."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    blocks: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not node.args:
            continue
        if not isinstance(node.func, ast.Attribute) or node.func.attr != "md":
            continue
        value = node.args[0]
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            blocks.append(value.value.strip())
    return blocks


def _plain_text(markdown: str) -> str:
    text = re.sub(r"\[([^]]+)]\([^)]+\)", r"\1", markdown)
    text = re.sub(r"`+([^`]+?)`+", r"``\1``", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"\1", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _inferred_title(path: Path) -> str:
    blocks = _markdown_blocks(path)
    for block in blocks:
        lines = block.splitlines()
        for line in lines:
            if not line.startswith("# "):
                continue
            title = _plain_text(line[2:])
            return title

    fallback = path.stem.removeprefix("example_").replace("_", " ").title()
    return fallback


def _metadata(path: Path) -> dict[str, str]:
    """Read ``# gallery_<key>: <value>`` comments."""
    metadata: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines()[:20]:
        match = re.match(r"# gallery_(\w+):\s*(.+)", line)
        if match:
            metadata[match.group(1)] = match.group(2).strip()
    return metadata


def _required_metadata(path: Path, metadata: dict[str, str], key: str) -> str:
    value = metadata.get(key)
    if value:
        return value
    relative = path.relative_to(PROJECT_ROOT)
    raise ValueError(f"{relative} is missing a required '# gallery_{key}: ...' tag")


def discover_examples() -> list[Example]:
    examples = []
    for path in sorted(EXAMPLES_DIR.rglob("example_*.py")):
        metadata = _metadata(path)
        inferred_title = _inferred_title(path)
        examples.append(
            Example(
                path,
                metadata.get("title", inferred_title),
                _required_metadata(path, metadata, "description"),
                _required_metadata(path, metadata, "category"),
            )
        )
    return examples


def render_gallery(examples: list[Example]) -> str:
    grouped: dict[str, list[Example]] = defaultdict(list)
    for example in examples:
        grouped[example.category].append(example)

    categories = list(CATEGORY_ORDER)
    categories.extend(sorted(set(grouped) - set(categories)))

    lines = [
        ".. This file is generated by docs/example_gallery.py. Do not edit it manually.",
        "",
        "================",
        "Examples Gallery",
        "================",
        "",
        "Rendered Marimo notebooks demonstrating ``pyFDN``. The gallery is generated",
        "automatically from every ``example_*.py`` file under ``examples/``.",
        "",
    ]

    for category in categories:
        entries = grouped.get(category, [])
        if not entries:
            continue
        lines.extend(
            [
                category,
                "-" * len(category),
                "",
                ".. list-table::",
                "   :widths: 35 65",
                "   :header-rows: 0",
                "",
            ]
        )
        for example in sorted(entries, key=lambda item: item.title.casefold()):
            url = f"_static/marimo/notebooks/{example.output_name}.html"
            lines.extend(
                [
                    f"   * - `{example.title} <{url}>`_",
                    f"     - {example.description}",
                ]
            )
        lines.append("")

    lines.extend(
        [
            "----",
            "",
            "All notebooks can also be browsed in the repository's",
            "`examples directory <https://github.com/artificial-audio/pyFDN/tree/main/examples>`_.",
            "",
        ]
    )
    return "\n".join(lines)


def generate_gallery(output_file: Path = OUTPUT_FILE) -> str:
    rendered = render_gallery(discover_examples())
    output_file.write_text(rendered, encoding="utf-8")
    return rendered


if __name__ == "__main__":
    generate_gallery()
